version: '3'

services:

  MY_WEB_SERVICE_NAME:
    image: python:3.8-slim
    command: python -m http.server --cgi 8000
    environment:
      PYTHONUNBUFFERED: 1
    volumes:
        - ./src:/var/www/html
        - ./static:/static
    ports:
      - "8000:8000"
    working_dir: ./src:/var/www/html

  MY_DB_SERVICE_NAME:
    build: ./python
    command: python main.py
    volumes:
        - ./src:/var/www/html
        - ./static:/static