version: '3'

services:

  MY_WEB_SERVICE_NAME:
    image: python:3.8-slim
    command: python -m http.server --cgi 8005
    environment:
      PYTHONUNBUFFERED: 1
    volumes:
        - ./src:/var/www/html
        - ./static:/static
    ports:
      - "8005:8005"
    working_dir: ./src:/var/www/html
