version: '3'

services:

  MY_WEB_SERVICE_NAME:
    image: PYTHON_VERSION
    command: python -m http.server --cgi 8005
    environment:
      PYTHONUNBUFFERED: 1
    ports:
      - "8005:8005"
    volumes:
      - ./src:/code
    working_dir: /code

  MY_DB_SERVICE_NAME:
    build: ./python
    environment:
      PYTHONUNBUFFERED: 1
    volumes:
      - ./src:/code
    working_dir: /code