version: '3'

services:

  MY_WEB_SERVICE_NAME:
    image: python:3.8-slim
    command: python -m http.server --cgi 8000
    volumes:
        - ./src:/code
        - ./static:/static
    ports:
      - "8000:8000"

  MY_DB_SERVICE_NAME:
    build: ./python
    command: python main.py
    volumes:
        - ./src:/code
        - ./static:/static